// Code generated by protoc-gen-easyrpc-go. DO NOT EDIT.
package conformancev1

import (
	easyrpc "github.com/easy-utils/easy-rpc-go"
)

// MethodSpecs for ConformanceService
func ConformanceService_Methods() []easyrpc.MethodSpec {
	return []easyrpc.MethodSpec{
		{Service: "easyrpc.conformance.v1.ConformanceService", Name: "Health", Path: "/v1/health", HTTPMethod: "GET", ClientStream: false, ServerStream: false, Body: ""},
		{Service: "easyrpc.conformance.v1.ConformanceService", Name: "Echo", Path: "/v1/echo", HTTPMethod: "POST", ClientStream: false, ServerStream: false, Body: "*"},
		{Service: "easyrpc.conformance.v1.ConformanceService", Name: "Count", Path: "/v1/count", HTTPMethod: "POST", ClientStream: false, ServerStream: true, Body: "*"},
		{Service: "easyrpc.conformance.v1.ConformanceService", Name: "Fail", Path: "/v1/fail", HTTPMethod: "POST", ClientStream: false, ServerStream: false, Body: "*"},
	}
}
