// Code generated by protoc-gen-easyrpc-go. DO NOT EDIT.
package conformancev1

import (
	easyrpc "github.com/easy-utils/easy-rpc-go"
	"context"
	"google.golang.org/protobuf/proto"
)

func ConformanceService_Methods() []easyrpc.MethodSpec {
	return []easyrpc.MethodSpec{
		{Service: "easyrpc.conformance.v1.ConformanceService", Name: "Health", Path: "/easyrpc.conformance.v1.ConformanceService/Health", ClientStream: false, ServerStream: false},
		{Service: "easyrpc.conformance.v1.ConformanceService", Name: "Echo", Path: "/easyrpc.conformance.v1.ConformanceService/Echo", ClientStream: false, ServerStream: false},
		{Service: "easyrpc.conformance.v1.ConformanceService", Name: "Count", Path: "/easyrpc.conformance.v1.ConformanceService/Count", ClientStream: false, ServerStream: true},
		{Service: "easyrpc.conformance.v1.ConformanceService", Name: "Fail", Path: "/easyrpc.conformance.v1.ConformanceService/Fail", ClientStream: false, ServerStream: false},
		{Service: "easyrpc.conformance.v1.ConformanceService", Name: "StreamFail", Path: "/easyrpc.conformance.v1.ConformanceService/StreamFail", ClientStream: false, ServerStream: true},
		{Service: "easyrpc.conformance.v1.ConformanceService", Name: "EchoMeta", Path: "/easyrpc.conformance.v1.ConformanceService/EchoMeta", ClientStream: false, ServerStream: false},
		{Service: "easyrpc.conformance.v1.ConformanceService", Name: "Big", Path: "/easyrpc.conformance.v1.ConformanceService/Big", ClientStream: false, ServerStream: false},
		{Service: "easyrpc.conformance.v1.ConformanceService", Name: "FailDetails", Path: "/easyrpc.conformance.v1.ConformanceService/FailDetails", ClientStream: false, ServerStream: false},
		{Service: "easyrpc.conformance.v1.ConformanceService", Name: "StreamFailDetails", Path: "/easyrpc.conformance.v1.ConformanceService/StreamFailDetails", ClientStream: false, ServerStream: true},
		{Service: "easyrpc.conformance.v1.ConformanceService", Name: "EchoTrailer", Path: "/easyrpc.conformance.v1.ConformanceService/EchoTrailer", ClientStream: false, ServerStream: false},
		{Service: "easyrpc.conformance.v1.ConformanceService", Name: "CountTrailer", Path: "/easyrpc.conformance.v1.ConformanceService/CountTrailer", ClientStream: false, ServerStream: true},
		{Service: "easyrpc.conformance.v1.ConformanceService", Name: "EchoBytes", Path: "/easyrpc.conformance.v1.ConformanceService/EchoBytes", ClientStream: false, ServerStream: false},
		{Service: "easyrpc.conformance.v1.ConformanceService", Name: "Sleep", Path: "/easyrpc.conformance.v1.ConformanceService/Sleep", ClientStream: false, ServerStream: false},
		{Service: "easyrpc.conformance.v1.ConformanceService", Name: "Empty", Path: "/easyrpc.conformance.v1.ConformanceService/Empty", ClientStream: false, ServerStream: false},
		{Service: "easyrpc.conformance.v1.ConformanceService", Name: "BigStream", Path: "/easyrpc.conformance.v1.ConformanceService/BigStream", ClientStream: false, ServerStream: true},
	}
}

type ConformanceServiceClient struct { rt easyrpc.Transport }
func NewConformanceServiceClient(rt easyrpc.Transport) *ConformanceServiceClient { return &ConformanceServiceClient{rt: rt} }

func (c *ConformanceServiceClient) Health(ctx context.Context, in *HealthRequest) (*HealthResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/easyrpc.conformance.v1.ConformanceService/Health", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &HealthResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *ConformanceServiceClient) Echo(ctx context.Context, in *EchoRequest) (*EchoResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/easyrpc.conformance.v1.ConformanceService/Echo", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &EchoResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *ConformanceServiceClient) Count(ctx context.Context, in *CountRequest) (easyrpc.Stream, error) {
	return c.rt.OpenStream(ctx, easyrpc.Request{URL: "/easyrpc.conformance.v1.ConformanceService/Count", Body: easyrpc.Frame(protoBytes(in), false)})
}

func (c *ConformanceServiceClient) Fail(ctx context.Context, in *FailRequest) (*FailResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/easyrpc.conformance.v1.ConformanceService/Fail", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &FailResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *ConformanceServiceClient) StreamFail(ctx context.Context, in *StreamFailRequest) (easyrpc.Stream, error) {
	return c.rt.OpenStream(ctx, easyrpc.Request{URL: "/easyrpc.conformance.v1.ConformanceService/StreamFail", Body: easyrpc.Frame(protoBytes(in), false)})
}

func (c *ConformanceServiceClient) EchoMeta(ctx context.Context, in *EchoMetaRequest) (*EchoMetaResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/easyrpc.conformance.v1.ConformanceService/EchoMeta", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &EchoMetaResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *ConformanceServiceClient) Big(ctx context.Context, in *BigRequest) (*BigResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/easyrpc.conformance.v1.ConformanceService/Big", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &BigResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *ConformanceServiceClient) FailDetails(ctx context.Context, in *FailDetailsRequest) (*FailDetailsResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/easyrpc.conformance.v1.ConformanceService/FailDetails", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &FailDetailsResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *ConformanceServiceClient) StreamFailDetails(ctx context.Context, in *StreamFailDetailsRequest) (easyrpc.Stream, error) {
	return c.rt.OpenStream(ctx, easyrpc.Request{URL: "/easyrpc.conformance.v1.ConformanceService/StreamFailDetails", Body: easyrpc.Frame(protoBytes(in), false)})
}

func (c *ConformanceServiceClient) EchoTrailer(ctx context.Context, in *EchoTrailerRequest) (*EchoTrailerResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/easyrpc.conformance.v1.ConformanceService/EchoTrailer", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &EchoTrailerResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *ConformanceServiceClient) CountTrailer(ctx context.Context, in *CountTrailerRequest) (easyrpc.Stream, error) {
	return c.rt.OpenStream(ctx, easyrpc.Request{URL: "/easyrpc.conformance.v1.ConformanceService/CountTrailer", Body: easyrpc.Frame(protoBytes(in), false)})
}

func (c *ConformanceServiceClient) EchoBytes(ctx context.Context, in *EchoBytesRequest) (*EchoBytesResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/easyrpc.conformance.v1.ConformanceService/EchoBytes", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &EchoBytesResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *ConformanceServiceClient) Sleep(ctx context.Context, in *SleepRequest) (*SleepResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/easyrpc.conformance.v1.ConformanceService/Sleep", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &SleepResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *ConformanceServiceClient) Empty(ctx context.Context, in *EmptyRequest) (*EmptyResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/easyrpc.conformance.v1.ConformanceService/Empty", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &EmptyResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *ConformanceServiceClient) BigStream(ctx context.Context, in *BigStreamRequest) (easyrpc.Stream, error) {
	return c.rt.OpenStream(ctx, easyrpc.Request{URL: "/easyrpc.conformance.v1.ConformanceService/BigStream", Body: easyrpc.Frame(protoBytes(in), false)})
}

type ConformanceServiceService interface {
	Health(ctx context.Context, in *HealthRequest) (*HealthResponse, error)
	Echo(ctx context.Context, in *EchoRequest) (*EchoResponse, error)
	Count(ctx context.Context, in *CountRequest, emit func(*CountResponse) error) error
	Fail(ctx context.Context, in *FailRequest) (*FailResponse, error)
	StreamFail(ctx context.Context, in *StreamFailRequest, emit func(*StreamFailResponse) error) error
	EchoMeta(ctx context.Context, in *EchoMetaRequest) (*EchoMetaResponse, error)
	Big(ctx context.Context, in *BigRequest) (*BigResponse, error)
	FailDetails(ctx context.Context, in *FailDetailsRequest) (*FailDetailsResponse, error)
	StreamFailDetails(ctx context.Context, in *StreamFailDetailsRequest, emit func(*StreamFailDetailsResponse) error) error
	EchoTrailer(ctx context.Context, in *EchoTrailerRequest) (*EchoTrailerResponse, error)
	CountTrailer(ctx context.Context, in *CountTrailerRequest, emit func(*CountTrailerResponse) error) error
	EchoBytes(ctx context.Context, in *EchoBytesRequest) (*EchoBytesResponse, error)
	Sleep(ctx context.Context, in *SleepRequest) (*SleepResponse, error)
	Empty(ctx context.Context, in *EmptyRequest) (*EmptyResponse, error)
	BigStream(ctx context.Context, in *BigStreamRequest, emit func(*BigStreamResponse) error) error
}

func RegisterConformanceServiceService(impl ConformanceServiceService) *easyrpc.ServiceRegistry {
	reg := easyrpc.NewServiceRegistry()
	reg.Unary["Health"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &HealthRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.Health(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["Echo"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &EchoRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.Echo(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Stream["Count"] = func(ctx context.Context, req []byte, emit func([]byte, bool) error) error {
		in := &CountRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return err }
		return impl.Count(ctx, in, func(out *CountResponse) error { return emit(protoBytes(out), false) })
	}
	reg.Unary["Fail"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &FailRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.Fail(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Stream["StreamFail"] = func(ctx context.Context, req []byte, emit func([]byte, bool) error) error {
		in := &StreamFailRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return err }
		return impl.StreamFail(ctx, in, func(out *StreamFailResponse) error { return emit(protoBytes(out), false) })
	}
	reg.Unary["EchoMeta"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &EchoMetaRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.EchoMeta(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["Big"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &BigRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.Big(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["FailDetails"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &FailDetailsRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.FailDetails(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Stream["StreamFailDetails"] = func(ctx context.Context, req []byte, emit func([]byte, bool) error) error {
		in := &StreamFailDetailsRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return err }
		return impl.StreamFailDetails(ctx, in, func(out *StreamFailDetailsResponse) error { return emit(protoBytes(out), false) })
	}
	reg.Unary["EchoTrailer"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &EchoTrailerRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.EchoTrailer(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Stream["CountTrailer"] = func(ctx context.Context, req []byte, emit func([]byte, bool) error) error {
		in := &CountTrailerRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return err }
		return impl.CountTrailer(ctx, in, func(out *CountTrailerResponse) error { return emit(protoBytes(out), false) })
	}
	reg.Unary["EchoBytes"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &EchoBytesRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.EchoBytes(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["Sleep"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &SleepRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.Sleep(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["Empty"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &EmptyRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.Empty(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Stream["BigStream"] = func(ctx context.Context, req []byte, emit func([]byte, bool) error) error {
		in := &BigStreamRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return err }
		return impl.BigStream(ctx, in, func(out *BigStreamResponse) error { return emit(protoBytes(out), false) })
	}
	return reg
}

func protoBytes(m proto.Message) []byte {
	b, _ := proto.Marshal(m)
	return b
}

