// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: easyrpc/conformance/v1/conformance.proto

package conformancev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_easyrpc_conformance_v1_conformance_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_easyrpc_conformance_v1_conformance_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type CountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountRequest) Reset() {
	*x = CountRequest{}
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRequest) ProtoMessage() {}

func (x *CountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRequest.ProtoReflect.Descriptor instead.
func (*CountRequest) Descriptor() ([]byte, []int) {
	return file_easyrpc_conformance_v1_conformance_proto_rawDescGZIP(), []int{2}
}

func (x *CountRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResponse) Reset() {
	*x = CountResponse{}
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResponse) ProtoMessage() {}

func (x *CountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResponse.ProtoReflect.Descriptor instead.
func (*CountResponse) Descriptor() ([]byte, []int) {
	return file_easyrpc_conformance_v1_conformance_proto_rawDescGZIP(), []int{3}
}

func (x *CountResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type FailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailRequest) Reset() {
	*x = FailRequest{}
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailRequest) ProtoMessage() {}

func (x *FailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailRequest.ProtoReflect.Descriptor instead.
func (*FailRequest) Descriptor() ([]byte, []int) {
	return file_easyrpc_conformance_v1_conformance_proto_rawDescGZIP(), []int{4}
}

func (x *FailRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailResponse) Reset() {
	*x = FailResponse{}
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailResponse) ProtoMessage() {}

func (x *FailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailResponse.ProtoReflect.Descriptor instead.
func (*FailResponse) Descriptor() ([]byte, []int) {
	return file_easyrpc_conformance_v1_conformance_proto_rawDescGZIP(), []int{5}
}

func (x *FailResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_easyrpc_conformance_v1_conformance_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_easyrpc_conformance_v1_conformance_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StreamFailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Emit this many data frames, then fail with `code`.
	EmitBefore    int32  `protobuf:"varint,1,opt,name=emit_before,json=emitBefore,proto3" json:"emit_before,omitempty"`
	Code          int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFailRequest) Reset() {
	*x = StreamFailRequest{}
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFailRequest) ProtoMessage() {}

func (x *StreamFailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFailRequest.ProtoReflect.Descriptor instead.
func (*StreamFailRequest) Descriptor() ([]byte, []int) {
	return file_easyrpc_conformance_v1_conformance_proto_rawDescGZIP(), []int{8}
}

func (x *StreamFailRequest) GetEmitBefore() int32 {
	if x != nil {
		return x.EmitBefore
	}
	return 0
}

func (x *StreamFailRequest) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StreamFailRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamFailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFailResponse) Reset() {
	*x = StreamFailResponse{}
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFailResponse) ProtoMessage() {}

func (x *StreamFailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFailResponse.ProtoReflect.Descriptor instead.
func (*StreamFailResponse) Descriptor() ([]byte, []int) {
	return file_easyrpc_conformance_v1_conformance_proto_rawDescGZIP(), []int{9}
}

func (x *StreamFailResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type EchoMetaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoMetaRequest) Reset() {
	*x = EchoMetaRequest{}
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoMetaRequest) ProtoMessage() {}

func (x *EchoMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoMetaRequest.ProtoReflect.Descriptor instead.
func (*EchoMetaRequest) Descriptor() ([]byte, []int) {
	return file_easyrpc_conformance_v1_conformance_proto_rawDescGZIP(), []int{10}
}

func (x *EchoMetaRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type EchoMetaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,2,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // mirrors selected request metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoMetaResponse) Reset() {
	*x = EchoMetaResponse{}
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoMetaResponse) ProtoMessage() {}

func (x *EchoMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoMetaResponse.ProtoReflect.Descriptor instead.
func (*EchoMetaResponse) Descriptor() ([]byte, []int) {
	return file_easyrpc_conformance_v1_conformance_proto_rawDescGZIP(), []int{11}
}

func (x *EchoMetaResponse) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *EchoMetaResponse) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type BigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int32                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BigRequest) Reset() {
	*x = BigRequest{}
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigRequest) ProtoMessage() {}

func (x *BigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigRequest.ProtoReflect.Descriptor instead.
func (*BigRequest) Descriptor() ([]byte, []int) {
	return file_easyrpc_conformance_v1_conformance_proto_rawDescGZIP(), []int{12}
}

func (x *BigRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type BigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BigResponse) Reset() {
	*x = BigResponse{}
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigResponse) ProtoMessage() {}

func (x *BigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigResponse.ProtoReflect.Descriptor instead.
func (*BigResponse) Descriptor() ([]byte, []int) {
	return file_easyrpc_conformance_v1_conformance_proto_rawDescGZIP(), []int{13}
}

func (x *BigResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FailDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DetailType    string                 `protobuf:"bytes,3,opt,name=detail_type,json=detailType,proto3" json:"detail_type,omitempty"` // ErrorDetail.type (a type URL)
	DetailText    string                 `protobuf:"bytes,4,opt,name=detail_text,json=detailText,proto3" json:"detail_text,omitempty"` // ErrorDetail.value bytes (UTF-8 text for testing)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailDetailsRequest) Reset() {
	*x = FailDetailsRequest{}
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailDetailsRequest) ProtoMessage() {}

func (x *FailDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailDetailsRequest.ProtoReflect.Descriptor instead.
func (*FailDetailsRequest) Descriptor() ([]byte, []int) {
	return file_easyrpc_conformance_v1_conformance_proto_rawDescGZIP(), []int{14}
}

func (x *FailDetailsRequest) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FailDetailsRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FailDetailsRequest) GetDetailType() string {
	if x != nil {
		return x.DetailType
	}
	return ""
}

func (x *FailDetailsRequest) GetDetailText() string {
	if x != nil {
		return x.DetailText
	}
	return ""
}

type FailDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailDetailsResponse) Reset() {
	*x = FailDetailsResponse{}
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailDetailsResponse) ProtoMessage() {}

func (x *FailDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailDetailsResponse.ProtoReflect.Descriptor instead.
func (*FailDetailsResponse) Descriptor() ([]byte, []int) {
	return file_easyrpc_conformance_v1_conformance_proto_rawDescGZIP(), []int{15}
}

func (x *FailDetailsResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type StreamFailDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmitBefore    int32                  `protobuf:"varint,1,opt,name=emit_before,json=emitBefore,proto3" json:"emit_before,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	DetailType    string                 `protobuf:"bytes,4,opt,name=detail_type,json=detailType,proto3" json:"detail_type,omitempty"`
	DetailText    string                 `protobuf:"bytes,5,opt,name=detail_text,json=detailText,proto3" json:"detail_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFailDetailsRequest) Reset() {
	*x = StreamFailDetailsRequest{}
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFailDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFailDetailsRequest) ProtoMessage() {}

func (x *StreamFailDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFailDetailsRequest.ProtoReflect.Descriptor instead.
func (*StreamFailDetailsRequest) Descriptor() ([]byte, []int) {
	return file_easyrpc_conformance_v1_conformance_proto_rawDescGZIP(), []int{16}
}

func (x *StreamFailDetailsRequest) GetEmitBefore() int32 {
	if x != nil {
		return x.EmitBefore
	}
	return 0
}

func (x *StreamFailDetailsRequest) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StreamFailDetailsRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StreamFailDetailsRequest) GetDetailType() string {
	if x != nil {
		return x.DetailType
	}
	return ""
}

func (x *StreamFailDetailsRequest) GetDetailText() string {
	if x != nil {
		return x.DetailText
	}
	return ""
}

type StreamFailDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFailDetailsResponse) Reset() {
	*x = StreamFailDetailsResponse{}
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFailDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFailDetailsResponse) ProtoMessage() {}

func (x *StreamFailDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_easyrpc_conformance_v1_conformance_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFailDetailsResponse.ProtoReflect.Descriptor instead.
func (*StreamFailDetailsResponse) Descriptor() ([]byte, []int) {
	return file_easyrpc_conformance_v1_conformance_proto_rawDescGZIP(), []int{17}
}

func (x *StreamFailDetailsResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

var File_easyrpc_conformance_v1_conformance_proto protoreflect.FileDescriptor

const file_easyrpc_conformance_v1_conformance_proto_rawDesc = "" +
	"\n" +
	"(easyrpc/conformance/v1/conformance.proto\x12\x16easyrpc.conformance.v1\x1a\x1cgoogle/api/annotations.proto\"#\n" +
	"\vEchoRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\"&\n" +
	"\fEchoResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\"$\n" +
	"\fCountRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"%\n" +
	"\rCountResponse\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\"'\n" +
	"\vFailRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x1e\n" +
	"\fFailResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x0f\n" +
	"\rHealthRequest\"4\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"b\n" +
	"\x11StreamFailRequest\x12\x1f\n" +
	"\vemit_before\x18\x01 \x01(\x05R\n" +
	"emitBefore\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"*\n" +
	"\x12StreamFailResponse\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\"'\n" +
	"\x0fEchoMetaRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\"\xa9\x01\n" +
	"\x10EchoMetaResponse\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\x12F\n" +
	"\x04meta\x18\x02 \x03(\v22.easyrpc.conformance.v1.EchoMetaResponse.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\" \n" +
	"\n" +
	"BigRequest\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\"!\n" +
	"\vBigResponse\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"\x84\x01\n" +
	"\x12FailDetailsRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vdetail_type\x18\x03 \x01(\tR\n" +
	"detailType\x12\x1f\n" +
	"\vdetail_text\x18\x04 \x01(\tR\n" +
	"detailText\"%\n" +
	"\x13FailDetailsResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xab\x01\n" +
	"\x18StreamFailDetailsRequest\x12\x1f\n" +
	"\vemit_before\x18\x01 \x01(\x05R\n" +
	"emitBefore\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vdetail_type\x18\x04 \x01(\tR\n" +
	"detailType\x12\x1f\n" +
	"\vdetail_text\x18\x05 \x01(\tR\n" +
	"detailText\"1\n" +
	"\x19StreamFailDetailsResponse\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index2\xc7\b\n" +
	"\x12ConformanceService\x12k\n" +
	"\x06Health\x12%.easyrpc.conformance.v1.HealthRequest\x1a&.easyrpc.conformance.v1.HealthResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/health\x12f\n" +
	"\x04Echo\x12#.easyrpc.conformance.v1.EchoRequest\x1a$.easyrpc.conformance.v1.EchoResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/echo\x12l\n" +
	"\x05Count\x12$.easyrpc.conformance.v1.CountRequest\x1a%.easyrpc.conformance.v1.CountResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/count0\x01\x12f\n" +
	"\x04Fail\x12#.easyrpc.conformance.v1.FailRequest\x1a$.easyrpc.conformance.v1.FailResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/fail\x12\x81\x01\n" +
	"\n" +
	"StreamFail\x12).easyrpc.conformance.v1.StreamFailRequest\x1a*.easyrpc.conformance.v1.StreamFailResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/stream-fail0\x01\x12w\n" +
	"\bEchoMeta\x12'.easyrpc.conformance.v1.EchoMetaRequest\x1a(.easyrpc.conformance.v1.EchoMetaResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/echo-meta\x12b\n" +
	"\x03Big\x12\".easyrpc.conformance.v1.BigRequest\x1a#.easyrpc.conformance.v1.BigResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/v1/big\x12\x83\x01\n" +
	"\vFailDetails\x12*.easyrpc.conformance.v1.FailDetailsRequest\x1a+.easyrpc.conformance.v1.FailDetailsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/fail-details\x12\x9e\x01\n" +
	"\x11StreamFailDetails\x120.easyrpc.conformance.v1.StreamFailDetailsRequest\x1a1.easyrpc.conformance.v1.StreamFailDetailsResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/stream-fail-details0\x01B@Z>github.com/easy-utils/easy-rpc-go/conformance/v1;conformancev1b\x06proto3"

var (
	file_easyrpc_conformance_v1_conformance_proto_rawDescOnce sync.Once
	file_easyrpc_conformance_v1_conformance_proto_rawDescData []byte
)

func file_easyrpc_conformance_v1_conformance_proto_rawDescGZIP() []byte {
	file_easyrpc_conformance_v1_conformance_proto_rawDescOnce.Do(func() {
		file_easyrpc_conformance_v1_conformance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_easyrpc_conformance_v1_conformance_proto_rawDesc), len(file_easyrpc_conformance_v1_conformance_proto_rawDesc)))
	})
	return file_easyrpc_conformance_v1_conformance_proto_rawDescData
}

var file_easyrpc_conformance_v1_conformance_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_easyrpc_conformance_v1_conformance_proto_goTypes = []any{
	(*EchoRequest)(nil),               // 0: easyrpc.conformance.v1.EchoRequest
	(*EchoResponse)(nil),              // 1: easyrpc.conformance.v1.EchoResponse
	(*CountRequest)(nil),              // 2: easyrpc.conformance.v1.CountRequest
	(*CountResponse)(nil),             // 3: easyrpc.conformance.v1.CountResponse
	(*FailRequest)(nil),               // 4: easyrpc.conformance.v1.FailRequest
	(*FailResponse)(nil),              // 5: easyrpc.conformance.v1.FailResponse
	(*HealthRequest)(nil),             // 6: easyrpc.conformance.v1.HealthRequest
	(*HealthResponse)(nil),            // 7: easyrpc.conformance.v1.HealthResponse
	(*StreamFailRequest)(nil),         // 8: easyrpc.conformance.v1.StreamFailRequest
	(*StreamFailResponse)(nil),        // 9: easyrpc.conformance.v1.StreamFailResponse
	(*EchoMetaRequest)(nil),           // 10: easyrpc.conformance.v1.EchoMetaRequest
	(*EchoMetaResponse)(nil),          // 11: easyrpc.conformance.v1.EchoMetaResponse
	(*BigRequest)(nil),                // 12: easyrpc.conformance.v1.BigRequest
	(*BigResponse)(nil),               // 13: easyrpc.conformance.v1.BigResponse
	(*FailDetailsRequest)(nil),        // 14: easyrpc.conformance.v1.FailDetailsRequest
	(*FailDetailsResponse)(nil),       // 15: easyrpc.conformance.v1.FailDetailsResponse
	(*StreamFailDetailsRequest)(nil),  // 16: easyrpc.conformance.v1.StreamFailDetailsRequest
	(*StreamFailDetailsResponse)(nil), // 17: easyrpc.conformance.v1.StreamFailDetailsResponse
	nil,                               // 18: easyrpc.conformance.v1.EchoMetaResponse.MetaEntry
}
var file_easyrpc_conformance_v1_conformance_proto_depIdxs = []int32{
	18, // 0: easyrpc.conformance.v1.EchoMetaResponse.meta:type_name -> easyrpc.conformance.v1.EchoMetaResponse.MetaEntry
	6,  // 1: easyrpc.conformance.v1.ConformanceService.Health:input_type -> easyrpc.conformance.v1.HealthRequest
	0,  // 2: easyrpc.conformance.v1.ConformanceService.Echo:input_type -> easyrpc.conformance.v1.EchoRequest
	2,  // 3: easyrpc.conformance.v1.ConformanceService.Count:input_type -> easyrpc.conformance.v1.CountRequest
	4,  // 4: easyrpc.conformance.v1.ConformanceService.Fail:input_type -> easyrpc.conformance.v1.FailRequest
	8,  // 5: easyrpc.conformance.v1.ConformanceService.StreamFail:input_type -> easyrpc.conformance.v1.StreamFailRequest
	10, // 6: easyrpc.conformance.v1.ConformanceService.EchoMeta:input_type -> easyrpc.conformance.v1.EchoMetaRequest
	12, // 7: easyrpc.conformance.v1.ConformanceService.Big:input_type -> easyrpc.conformance.v1.BigRequest
	14, // 8: easyrpc.conformance.v1.ConformanceService.FailDetails:input_type -> easyrpc.conformance.v1.FailDetailsRequest
	16, // 9: easyrpc.conformance.v1.ConformanceService.StreamFailDetails:input_type -> easyrpc.conformance.v1.StreamFailDetailsRequest
	7,  // 10: easyrpc.conformance.v1.ConformanceService.Health:output_type -> easyrpc.conformance.v1.HealthResponse
	1,  // 11: easyrpc.conformance.v1.ConformanceService.Echo:output_type -> easyrpc.conformance.v1.EchoResponse
	3,  // 12: easyrpc.conformance.v1.ConformanceService.Count:output_type -> easyrpc.conformance.v1.CountResponse
	5,  // 13: easyrpc.conformance.v1.ConformanceService.Fail:output_type -> easyrpc.conformance.v1.FailResponse
	9,  // 14: easyrpc.conformance.v1.ConformanceService.StreamFail:output_type -> easyrpc.conformance.v1.StreamFailResponse
	11, // 15: easyrpc.conformance.v1.ConformanceService.EchoMeta:output_type -> easyrpc.conformance.v1.EchoMetaResponse
	13, // 16: easyrpc.conformance.v1.ConformanceService.Big:output_type -> easyrpc.conformance.v1.BigResponse
	15, // 17: easyrpc.conformance.v1.ConformanceService.FailDetails:output_type -> easyrpc.conformance.v1.FailDetailsResponse
	17, // 18: easyrpc.conformance.v1.ConformanceService.StreamFailDetails:output_type -> easyrpc.conformance.v1.StreamFailDetailsResponse
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_easyrpc_conformance_v1_conformance_proto_init() }
func file_easyrpc_conformance_v1_conformance_proto_init() {
	if File_easyrpc_conformance_v1_conformance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_easyrpc_conformance_v1_conformance_proto_rawDesc), len(file_easyrpc_conformance_v1_conformance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_easyrpc_conformance_v1_conformance_proto_goTypes,
		DependencyIndexes: file_easyrpc_conformance_v1_conformance_proto_depIdxs,
		MessageInfos:      file_easyrpc_conformance_v1_conformance_proto_msgTypes,
	}.Build()
	File_easyrpc_conformance_v1_conformance_proto = out.File
	file_easyrpc_conformance_v1_conformance_proto_goTypes = nil
	file_easyrpc_conformance_v1_conformance_proto_depIdxs = nil
}
