// Code generated by protoc-gen-easyrpc-go. DO NOT EDIT.
package v1

import (
	easyrpc "github.com/easy-utils/easy-rpc-go"
	"context"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

func ConformanceService_Methods() []easyrpc.MethodSpec {
	return []easyrpc.MethodSpec{
		{Service: "connectrpc.conformance.v1.ConformanceService", Name: "Unary", Path: "/connectrpc.conformance.v1.ConformanceService/Unary", ClientStream: false, ServerStream: false},
		{Service: "connectrpc.conformance.v1.ConformanceService", Name: "ServerStream", Path: "/connectrpc.conformance.v1.ConformanceService/ServerStream", ClientStream: false, ServerStream: true},
		{Service: "connectrpc.conformance.v1.ConformanceService", Name: "ClientStream", Path: "/connectrpc.conformance.v1.ConformanceService/ClientStream", ClientStream: false, ServerStream: false},
		{Service: "connectrpc.conformance.v1.ConformanceService", Name: "BidiStream", Path: "/connectrpc.conformance.v1.ConformanceService/BidiStream", ClientStream: false, ServerStream: true},
		{Service: "connectrpc.conformance.v1.ConformanceService", Name: "Unimplemented", Path: "/connectrpc.conformance.v1.ConformanceService/Unimplemented", ClientStream: false, ServerStream: false},
		{Service: "connectrpc.conformance.v1.ConformanceService", Name: "IdempotentUnary", Path: "/connectrpc.conformance.v1.ConformanceService/IdempotentUnary", ClientStream: false, ServerStream: false},
	}
}

type ConformanceServiceClient struct { rt easyrpc.Transport }
func NewConformanceServiceClient(rt easyrpc.Transport) *ConformanceServiceClient { return &ConformanceServiceClient{rt: rt} }

func (c *ConformanceServiceClient) Unary(ctx context.Context, in *UnaryRequest, opts ...easyrpc.CallOption) (*UnaryResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/connectrpc.conformance.v1.ConformanceService/Unary", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &UnaryResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *ConformanceServiceClient) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...easyrpc.CallOption) (easyrpc.Stream, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	return c.rt.OpenStream(ctx, easyrpc.Request{URL: "/connectrpc.conformance.v1.ConformanceService/ServerStream", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(true, kind)}}, Body: easyrpc.Frame(encodeMsg(in, kind), false)})
}

func (c *ConformanceServiceClient) ClientStream(ctx context.Context, in *ClientStreamRequest, opts ...easyrpc.CallOption) (*ClientStreamResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/connectrpc.conformance.v1.ConformanceService/ClientStream", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ClientStreamResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *ConformanceServiceClient) BidiStream(ctx context.Context, in *BidiStreamRequest, opts ...easyrpc.CallOption) (easyrpc.Stream, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	return c.rt.OpenStream(ctx, easyrpc.Request{URL: "/connectrpc.conformance.v1.ConformanceService/BidiStream", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(true, kind)}}, Body: easyrpc.Frame(encodeMsg(in, kind), false)})
}

func (c *ConformanceServiceClient) Unimplemented(ctx context.Context, in *UnimplementedRequest, opts ...easyrpc.CallOption) (*UnimplementedResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/connectrpc.conformance.v1.ConformanceService/Unimplemented", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &UnimplementedResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *ConformanceServiceClient) IdempotentUnary(ctx context.Context, in *IdempotentUnaryRequest, opts ...easyrpc.CallOption) (*IdempotentUnaryResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/connectrpc.conformance.v1.ConformanceService/IdempotentUnary", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &IdempotentUnaryResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

type ConformanceServiceService interface {
	Unary(ctx context.Context, in *UnaryRequest) (*UnaryResponse, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, emit func(*ServerStreamResponse) error) error
	ClientStream(ctx context.Context, in *ClientStreamRequest) (*ClientStreamResponse, error)
	BidiStream(ctx context.Context, in *BidiStreamRequest, emit func(*BidiStreamResponse) error) error
	Unimplemented(ctx context.Context, in *UnimplementedRequest) (*UnimplementedResponse, error)
	IdempotentUnary(ctx context.Context, in *IdempotentUnaryRequest) (*IdempotentUnaryResponse, error)
}

func RegisterConformanceServiceService(impl ConformanceServiceService) *easyrpc.ServiceRegistry {
	reg := easyrpc.NewServiceRegistry()
	reg.Unary["Unary"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &UnaryRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.Unary(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Stream["ServerStream"] = func(ctx context.Context, req []byte, emit func([]byte, bool) error) error {
		in := &ServerStreamRequest{}
		if err := decodeMsg(req, in, easyrpc.HandlerContextFromContext(ctx).Kind); err != nil { return err }
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		return impl.ServerStream(ctx, in, func(out *ServerStreamResponse) error { return emit(encodeMsg(out, kind), false) })
	}
	reg.Unary["ClientStream"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ClientStreamRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.ClientStream(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Stream["BidiStream"] = func(ctx context.Context, req []byte, emit func([]byte, bool) error) error {
		in := &BidiStreamRequest{}
		if err := decodeMsg(req, in, easyrpc.HandlerContextFromContext(ctx).Kind); err != nil { return err }
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		return impl.BidiStream(ctx, in, func(out *BidiStreamResponse) error { return emit(encodeMsg(out, kind), false) })
	}
	reg.Unary["Unimplemented"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &UnimplementedRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.Unimplemented(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["IdempotentUnary"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &IdempotentUnaryRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.IdempotentUnary(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	return reg
}

func protoBytes(m proto.Message) []byte {
	b, _ := proto.Marshal(m)
	return b
}

func encodeMsg(m proto.Message, kind easyrpc.ContentKind) []byte {
	if kind == easyrpc.KindJSON {
		b, err := protojson.Marshal(m)
		if err != nil {
			return []byte("{}")
		}
		return b
	}
	return protoBytes(m)
}

func decodeMsg(b []byte, m proto.Message, kind easyrpc.ContentKind) error {
	if kind == easyrpc.KindJSON {
		return protojson.UnmarshalOptions{DiscardUnknown: true}.Unmarshal(b, m)
	}
	return proto.Unmarshal(b, m)
}
