// Code generated by protoc-gen-easyrpc-go. DO NOT EDIT.
package v1

import (
	easyrpc "github.com/easy-utils/easy-rpc-go"
	"context"
	"google.golang.org/protobuf/proto"
)

func ConformanceService_Methods() []easyrpc.MethodSpec {
	return []easyrpc.MethodSpec{
		{Service: "connectrpc.conformance.v1.ConformanceService", Name: "Unary", Path: "/connectrpc.conformance.v1.ConformanceService/Unary", ClientStream: false, ServerStream: false},
		{Service: "connectrpc.conformance.v1.ConformanceService", Name: "ServerStream", Path: "/connectrpc.conformance.v1.ConformanceService/ServerStream", ClientStream: false, ServerStream: true},
		{Service: "connectrpc.conformance.v1.ConformanceService", Name: "ClientStream", Path: "/connectrpc.conformance.v1.ConformanceService/ClientStream", ClientStream: false, ServerStream: false},
		{Service: "connectrpc.conformance.v1.ConformanceService", Name: "BidiStream", Path: "/connectrpc.conformance.v1.ConformanceService/BidiStream", ClientStream: false, ServerStream: true},
		{Service: "connectrpc.conformance.v1.ConformanceService", Name: "Unimplemented", Path: "/connectrpc.conformance.v1.ConformanceService/Unimplemented", ClientStream: false, ServerStream: false},
		{Service: "connectrpc.conformance.v1.ConformanceService", Name: "IdempotentUnary", Path: "/connectrpc.conformance.v1.ConformanceService/IdempotentUnary", ClientStream: false, ServerStream: false},
	}
}

type ConformanceServiceClient struct { rt easyrpc.Transport }
func NewConformanceServiceClient(rt easyrpc.Transport) *ConformanceServiceClient { return &ConformanceServiceClient{rt: rt} }

func (c *ConformanceServiceClient) Unary(ctx context.Context, in *UnaryRequest) (*UnaryResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/connectrpc.conformance.v1.ConformanceService/Unary", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &UnaryResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *ConformanceServiceClient) ServerStream(ctx context.Context, in *ServerStreamRequest) (easyrpc.Stream, error) {
	return c.rt.OpenStream(ctx, easyrpc.Request{URL: "/connectrpc.conformance.v1.ConformanceService/ServerStream", Body: easyrpc.Frame(protoBytes(in), false)})
}

func (c *ConformanceServiceClient) ClientStream(ctx context.Context, in *ClientStreamRequest) (*ClientStreamResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/connectrpc.conformance.v1.ConformanceService/ClientStream", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ClientStreamResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *ConformanceServiceClient) BidiStream(ctx context.Context, in *BidiStreamRequest) (easyrpc.Stream, error) {
	return c.rt.OpenStream(ctx, easyrpc.Request{URL: "/connectrpc.conformance.v1.ConformanceService/BidiStream", Body: easyrpc.Frame(protoBytes(in), false)})
}

func (c *ConformanceServiceClient) Unimplemented(ctx context.Context, in *UnimplementedRequest) (*UnimplementedResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/connectrpc.conformance.v1.ConformanceService/Unimplemented", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &UnimplementedResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *ConformanceServiceClient) IdempotentUnary(ctx context.Context, in *IdempotentUnaryRequest) (*IdempotentUnaryResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/connectrpc.conformance.v1.ConformanceService/IdempotentUnary", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &IdempotentUnaryResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

type ConformanceServiceService interface {
	Unary(ctx context.Context, in *UnaryRequest) (*UnaryResponse, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, emit func(*ServerStreamResponse) error) error
	ClientStream(ctx context.Context, in *ClientStreamRequest) (*ClientStreamResponse, error)
	BidiStream(ctx context.Context, in *BidiStreamRequest, emit func(*BidiStreamResponse) error) error
	Unimplemented(ctx context.Context, in *UnimplementedRequest) (*UnimplementedResponse, error)
	IdempotentUnary(ctx context.Context, in *IdempotentUnaryRequest) (*IdempotentUnaryResponse, error)
}

func RegisterConformanceServiceService(impl ConformanceServiceService) *easyrpc.ServiceRegistry {
	reg := easyrpc.NewServiceRegistry()
	reg.Unary["Unary"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &UnaryRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.Unary(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Stream["ServerStream"] = func(ctx context.Context, req []byte, emit func([]byte, bool) error) error {
		in := &ServerStreamRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return err }
		return impl.ServerStream(ctx, in, func(out *ServerStreamResponse) error { return emit(protoBytes(out), false) })
	}
	reg.Unary["ClientStream"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ClientStreamRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.ClientStream(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Stream["BidiStream"] = func(ctx context.Context, req []byte, emit func([]byte, bool) error) error {
		in := &BidiStreamRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return err }
		return impl.BidiStream(ctx, in, func(out *BidiStreamResponse) error { return emit(protoBytes(out), false) })
	}
	reg.Unary["Unimplemented"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &UnimplementedRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.Unimplemented(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["IdempotentUnary"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &IdempotentUnaryRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.IdempotentUnary(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	return reg
}

func protoBytes(m proto.Message) []byte {
	b, _ := proto.Marshal(m)
	return b
}

